---
title: "Export simulation to C++"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Export simulation to C++}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This package export and compiles simulations from the open systems pharmacology suite. The class SimulationCompiled allows to initialize, modify and run those simulations afterwards.

```{r exportSimulation}
library(ospsuiteCpp)
# Load simulation
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)
par <- c("Aciclovir|Lipophilicity",
         "Aciclovir|Fraction unbound (plasma)")
# select free parameter, export and compile
opt = SimulationBatchOptions$new(variableParameters = par, variableMolecules = NULL)
cppFile = exportSimulationCpp(sim, opt, outputName = "Aciclovir")
dllFile = compileSimulationCpp(cppFile)

# initialize simulation, run once with the default paramter, change time grid and parameter and run again
sim = SimulationCompiled$new('Aciclovir')
parameter = sim$getP()
res1 = sim$run(parameter)
tgrid = sim$getT()
sim$setT(c(tgrid, tgrid[length(tgrid)]+1.0))
parameter[1] = parameter[1] + 0.1
res2 = sim$run(parameter)

```
